export default [
  { "title": "Avatar Homepage Image", "author": "Deviant Art", "url": "https://imgur.com/60O6QxQ" },
  { "title": "Avatar Background 1", "author": "Official Avatar Site", "url": "https://www.youtube.com/@TeamAvatar" },
  { "title": "Avatar Background 2", "author": "Official Avatar Site", "url": "https://www.youtube.com/@TeamAvatar" },
  { "title": "Avatar Background 3", "author": "Reddit", "url": "https://www.reddit.com/r/wallpaper/comments/i74kf2/1920x1080_the_dragon_prince_wallpaper/?utm_source=ifttt" },
  { "title": "Avatar Background 4", "author": "Official Avatar Site", "url": "https://www.youtube.com/@TeamAvatar" },
  { "title": "Avatar Background 5", "author": "Official Avatar Site", "url": "https://www.youtube.com/@TeamAvatar" },
  { "title": "Avatar Background 6", "author": "Official Avatar Site", "url": "https://www.youtube.com/@TeamAvatar" },
  { "title": "Avatar Background 7", "author": "Official Avatar Site", "url": "https://www.youtube.com/@TeamAvatar" },
  { "title": "Avatar Background 8", "author": "Official Avatar Site", "url": "https://www.youtube.com/@TeamAvatar" },
  { "title": "Avatar Background 9", "author": "Official Avatar Site", "url": "https://www.youtube.com/@TeamAvatar" },
  { "title": "Avatar Background 10", "author": "Official Avatar Site", "url": "https://www.youtube.com/@TeamAvatar" },
  { "title": "Avatar Background 11", "author": "Valonia Feline", "url": "https://www.deviantart.com/valonia-feline/art/Avatar-The-last-Airbender-896323249" },
  { "title": "Avatar Background 12", "author": "Naomi VanDoren", "url": "https://freerbarar.pics/product_details/79671727.html" },
  { "title": "Avatar Background 13", "author": "Official Avatar Site", "url": "https://www.youtube.com/@TeamAvatar" },
  { "title": "Avatar Background 14", "author": "Official Avatar Site", "url": "https://www.youtube.com/@TeamAvatar" },
  { "title": "Avatar Background 15", "author": "Official Avatar Site", "url": "https://www.youtube.com/@TeamAvatar" },
  { "title": "All Character Portraits", "author": "Official Avatar Site", "url": "https://www.youtube.com/@TeamAvatar" },
  { "title": "Avatar Logo", "author": "Official Avatar Site", "url": "https://www.youtube.com/@TeamAvatar" },
]