export default [
  '/backgrounds/avatar-landscape1.jpg',
  '/backgrounds/avatar-landscape2.png',
  '/backgrounds/avatar-landscape3.png',
  '/backgrounds/avatar-landscape4.png',
  '/backgrounds/avatar-landscape5.webp',
  '/backgrounds/avatar-landscape6.avif',
  '/backgrounds/avatar-landscape7.jpg',
  '/backgrounds/avatar-landscape8.png',
  '/backgrounds/avatar-landscape9.jpg',
  '/backgrounds/avatar-landscape10.jpg',
  '/backgrounds/avatar-landscape11.jpg',
  '/backgrounds/avatar-landscape12.jpg',
  '/backgrounds/avatar-landscape13.webp',
  '/backgrounds/avatar-landscape14.avif',
  '/backgrounds/avatar-landscape15.jpg',
];
